blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/DobroslavRadosavljevic/awesome-minecraft-hostings/discussions
    about: Ask questions or discuss ideas
